package palia.algorithm.callback;

public enum PaliaMinerStatus {
	EXTRACT_LOG_VARIANTS, SIMPLE_ACCEPTOR_TREE, CONSECUTIVE_MERGE, REMOVE_REPEATED_TRANSITIONS, FUSE_END_NODES,
	FUSE_MILESTONES, MINE_ONWARD_MERGE_1, PARALLEL_FORWARD_MERGE, MINE_ONWARD_MERGE_2;
}
